#ifndef ZYNTERCEPT_SYSCALL_H
#define ZYNTERCEPT_SYSCALL_H

#if defined(WIN32) || defined(_WIN32) || defined(_WIN64) || defined(__CYGWIN__)
#include <Zyntercept/Core/Syscall/Windows/Windows.h>

#define ZYNTERCEPT_WINDOWS

#define ZynterceptIs64BitSystem ZynterceptIs64BitSystemWindows
#define ZynterceptIs32BitSystem ZynterceptIs32BitSystemWindows
#define ZynterceptIs32BitProcess ZynterceptIs32BitProcessWindows
#define ZynterceptIs64BitProcess ZynterceptIs64BitProcessWindows
#define ZynterceptIsUnsupportedProcessArchitecture ZynterceptIsUnsupportedProcessArchitectureWindows
#define ZynterceptIsCurrentProcess ZynterceptIsCurrentProcessWindows
#define ZynterceptVirtualMemoryInformation ZynterceptVirtualMemoryInformationWindows
#define ZynterceptAllocateMemory ZynterceptAllocateMemoryWindows
#define ZynterceptReleaseMemory ZynterceptReleaseMemoryWindows
#define ZynterceptProtectMemory ZynterceptProtectMemoryWindows
#define ZynterceptQueryMemory ZynterceptQueryMemoryWindows
#define ZynterceptWriteMemory ZynterceptWriteMemoryWindows
#define ZynterceptReadMemory ZynterceptReadMemoryWindows
#define ZynterceptFlushMicroprocessorCache ZynterceptFlushMicroprocessorCacheWindows
#define ZynterceptAtomicWriteMemory ZynterceptAtomicWriteMemoryWindows

#elif defined(__linux__) || defined(unix) || defined(__unix__) || defined(__unix)
#include <Zyntercept/Core/Syscall/Unix/Unix.h>

#define ZYNTERCEPT_UNIX

#define ZynterceptIs64BitSystem ZynterceptIs64BitSystemUnix
#define ZynterceptIs32BitSystem ZynterceptIs32BitSystemUnix
#define ZynterceptIs32BitProcess ZynterceptIs32BitProcessUnix
#define ZynterceptIs64BitProcess ZynterceptIs64BitProcessUnix
#define ZynterceptIsUnsupportedProcessArchitecture ZynterceptIsUnsupportedProcessArchitectureUnix
#define ZynterceptIsCurrentProcess ZynterceptIsCurrentProcessUnix
#define ZynterceptVirtualMemoryInformation ZynterceptVirtualMemoryInformationUnix
#define ZynterceptAllocateMemory ZynterceptAllocateMemoryUnix
#define ZynterceptReleaseMemory ZynterceptReleaseMemoryUnix
#define ZynterceptProtectMemory ZynterceptProtectMemoryUnix
#define ZynterceptQueryMemory ZynterceptQueryMemoryUnix
#define ZynterceptWriteMemory ZynterceptWriteMemoryUnix
#define ZynterceptReadMemory ZynterceptReadMemoryUnix
#define ZynterceptFlushMicroprocessorCache ZynterceptFlushMicroprocessorCacheUnix
#define ZynterceptAtomicWriteMemory ZynterceptAtomicWriteMemoryUnix

#else
#error Zyntercept can only be built in Windows or Unix operating systems
#endif

#endif // ZYNTERCEPT_SYSCALL_H
